module.exports = {
  parserPreset: './parser-preset',
  formatter: '@commitlint/format',
  rules: {
    'body-leading-blank': [2, 'always'],
    'body-max-line-length': [2, 'always', 72],
    'body-max-length': [0],
    'body-min-length': [0],
    'footer-leading-blank': [2, 'always'],
    'footer-max-length': [0],
    'footer-min-length': [0],
    'header-max-length': [2, 'always', 72],
    'header-min-length': [1, 'always', 30],
    'scope-case': [0],
    'scope-empty': [0],
    'scope-max-length': [0],
    'scope-min-length': [0],
    'subject-case': [2, 'always', 'sentence-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never'],
    'subject-max-length': [0],
    'subject-min-length': [0],
    'type-case': [0],
    'type-empty': [2, 'always'],
    'type-enum': [2, 'never'],
    'type-max-length': [0],
    'type-min-length': [0],
  },
  defaultIgnores: true,
};
